# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master

pool:
  vmImage: ubuntu-latest
  
variables:
  - group: alert-bot-variables

jobs: 
  - job: BuildJob
    displayName: Builds the maven file, composes a Docker Image, and pushes the Docker image to Azure Container Registry
    steps:
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.17'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          goals: 'package'

      - task: Maven@3
        displayName: Build Docker image
        inputs:
          mavenPomFile: 'pom.xml'
          goals: 'spring-boot:build-image'
          publishJUnitResults: false
          jdkVersionOption: '1.17'
      
      - task: Docker@2
        inputs:
          containerRegistry: 'jdlContainersConnection'
          repository: 'alert-bot'
          command: 'push'
          tags: 'latest'
      - script: echo Test key is $(test-discord-bot-key)
        displayName: Run Variable Group test
