# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master

pool:
  vmImage: ubuntu-latest


jobs: 
  - job: BuildJob
    displayName: Build Job
    steps:
      - task: Maven@3
        displayName: Compile Maven artefact.
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.17'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          goals: 'package'

      - task: Maven@3
        displayName: Build Docker image
        inputs:
          mavenPomFile: 'pom.xml'
          goals: 'spring-boot:build-image'
          publishJUnitResults: false
          jdkVersionOption: '1.17'
      
      - task: Docker@2
        displayName: Push Docker image to Azure Container Repository.
        inputs:
          containerRegistry: 'jdlContainersConnection'
          repository: 'alert-bot'
          command: 'push'
          tags: 'latest'